### ISSUE TITLE
Manually creating 3D text node does not seem to work

### ISSUE THREAD

**Issue by tom-leys** [SIsilicon/Godot-3D-text-plugin#3]
Steps to reproduce:
1. Create a new scene, with a 3D spatial parent.
2. Create a Spatial child. This is going to be the 3D label.
3. Drag label_3d.gd from /addons/SIsilicon.3d.text/label_3d.gd and drop it on the new child spatial (from step 2)
4. Edit the options on the RHS so that the label has some contents, it's centered, etc.

Expected: 
Should see a label

Result: 
I could not get a label to appear, even though I was trying to copy the options from the other example.

Note: I noticed output 
 res://addons/SIsilicon.3d.text/label_3d.gd:56 - Invalid set index 'text' (on base: 'Nil') with value of type 'String'.

Workaround:
Saving the new scene and re-opening seems to fix the issue.

....

However - this isn't a real solution because I get an exception when I run my game and use the scene.

The function below (in label_3d.gd) is called too early:
`
func set_text(string):
	text = string;
	label.text = text
	label.rect_size = Vector2()
	label.force_update_transform()
`
This function is called BEFORE _ready() has created label or viewport. This means that the debugger throws an exception.

**Comment by SIsilicon** [comment]
Reopening it would make it work because the nodes that the `Label3D` uses are created when the `_ready` function is invoked. The reason why just adding the script to a Spatial doesn't work is because the `_ready` function doesn't get called since the node is already in the scene before the script was attached. Therefore it should work if the script was attached to the node _before_ it is added to the scene.

As for the other error, I went ahead and fixed it. :)
